### ISSUE TITLE
Steps are inappropriately skipped even when changed files match the filter

### ISSUE THREAD

**Issue by tylerlaprade** [tony84727/changed-file-filter#47]
I made a PR with three commits in it. The final commit only touched a few files, so the changed file filter thought only those files were changed, and my other actions were skipped.

**Comment by tony84727** [comment]
Hello, did some of the changes get merged into the target branch first?

Because the action uses `git diff` to compare versions of source branch and target branch.

Say, the pull requests consists of three commits. But the first commit was cherry-picked by others and merged into the same target branch (normally `main` or `master`). When next time the action runs, changes of the first commit will be excluded from the diff and not reported as changed.

**Comment by tylerlaprade** [comment]
No, none of the commits were merged. All were still pending, and the changed file filter skipped out lints and tests without us realizing, so we merged the entire PR all at once.

**Comment by tylerlaprade** [comment]
Update on this issue:
The "multiple commits" may have been a red herring. I just observed the same behavior on a PR with only one commit.
```yaml
runs:
  using: 'composite'
  steps:
    - uses: tony84727/changed-file-filter@v0.2.3
      id: filter
      with:
        filters: |
          hanaq:
            - '.github/**/*'
            - 'hanaq/**/*'
            - '.ruff.toml'
            - 'pyrightconfig.json'
          paqarina:
            - '.github/**/*'
            - 'paqarina/**/*'
```
![image](https://github.com/user-attachments/assets/5ba5fa59-6160-4ce6-966a-5036294f07d7)

I verified in the GitHub Action logs that these `paqarina/` files were in the (long) list of files that were changed. Could they have been excluded because they were at the very end, or what happened here?
